### ISSUE TITLE
Not sure why container shell is set to current shell

### ISSUE THREAD

**Issue by jpambrun** [gportay/dosh#2]
I use zsh and most images dont have zsh.
It's not obvious that users need to run 'SHELL=/bin/bash dosh' to get it to work properly in that scenario.
I would suggest defaulting to bash while providing an command line option (other than just --sh) .

With that said, I'm am new to this docker thing and it really look like this tool can help me get a grip of the permission issues.

**Comment by gportay** [comment]
Indeed. And some images have only `/bin/sh` (alpine is based on busybox; it has only sh and ash).

That is why I introduced the `--sh` option to set `$SHELL` to `/bin/sh`. But right, maybe you may want to set your own shell interpreter.

I will give a try to a new shell option `--shell /path/to/shell` and see.

**Comment by jpambrun** [comment]
I guess I wonder what is the purpose of using the same shell as the host by default? Useless you use bash, it probably wont be there, right?

**Comment by gportay** [comment]
Well... the only shell we can trust is `/bin/sh`. At least it should be a symlink to another shell interpreter such as bash, dash...

I guess most of desktop distros are using bash; and it would be wiser if `/bin/bash` is set a the default shell interpreter of dosh.

But I do not really like the idea of hardcoding it into dosh; because it may not be installed in the container.

Also I was thinking about writing `.doshrc` and `.dosh_profile` files that are sourced by dosh.

I cannot tell yet what should be done :/

**Comment by jpambrun** [comment]
Nor do I.. put s and have some way to launch $SHELL or bash if it exist?

**Comment by gportay** [comment]
After reflexion, you are right, dosh should start `/bin/sh` (hardcoded) and must no rely in `$SHELL` since this interpreter is not necessarly installed in the docker image.

```
gportay@gportay ~/src/dosh $ ./dosh
$ echo $0
/bin/sh
```

To overwrite the shell, there are two ways

1. Using `--shell SHELL` option
```
gportay@gportay ~/src/dosh $ ./dosh --shell /bin/zsh
e2b18bb85cfe% echo $0
/bin/zsh
```

2. Using `DOSHELL=/bin/zsh` environment variable
```
gportay@gportay ~/src/dosh $ DOSHELL=/bin/zsh ./dosh
216a612255e6% echo $0
/bin/zsh
```

A more convenient way is to set and export `DOSHELL` in `~/.profile`, `~/.bash_profile`, `~/./bashrc`, `~/.zshrc` or whatever dot-profile.
